### ISSUE TITLE
NoClassDefFoundError: org/codehaus/jackson/JsonFactory

### ISSUE THREAD

**Issue by Adam-Origamiiris** [GoogleCloudPlatform/gcloud-intellij#169]
What version of IDEA are you using?
IntelliJ community Edition 14.1.5
What version of Java are you using?
Java 1.8.0_60 on CentOS 6.7
What did you do?
Installed both plugins with settings, Plugins Install plugin from disk and added Google Cloud Tools Core and Google Logini.
New Project, then VCS > Checkout from Version Control > Google Cloud 
Then Cloud Project Enter Project ID, the Google sign in pop up appears. 
Click on Sign on  
What did you expect to see?
The google login window in the browser
What did you see instead?
PM NoClassDefFoundError: org/codehaus/jackson/JsonFactory

**Comment by elharo** [comment]
Did you build the plugins with gradle or from inside IDEA?

Sounds like we're failing to bundle a dependency somewhere.

**Comment by elharo** [comment]
I can reproduce this from the gradle build. I think I know what's missing.

**Comment by elharo** [comment]
elharo@elharo:~$ idea.sh
[  12891]  ERROR - llij.ide.plugins.PluginManager - org/codehaus/jackson/JsonFactory 
java.lang.NoClassDefFoundError: org/codehaus/jackson/JsonFactory
	at com.google.api.client.json.jackson.JacksonFactory.<init>(JacksonFactory.java:44)
	at com.google.gdt.eclipse.login.common.GoogleLoginState.<clinit>(GoogleLoginState.java:60)
	at com.google.gct.login.GoogleLogin.createGoogleLoginState(Unknown Source)
	at com.google.gct.login.GoogleLogin.logIn(Unknown Source)
	at com.google.gct.idea.elysium.ProjectSelector$PopupPanel.doLogin(Unknown Source)
	at com.google.gct.login.ui.GoogleLoginEmptyPanel$1.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
