### ISSUE TITLE
exception occurs during test runs

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#181]
This doesn't seem to affect the success of the test run.

ERROR: @NotNull method com/intellij/openapi/vfs/VirtualFileManager.getInstance must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/openapi/vfs/VirtualFileManager.getInstance must not return null
	at com.intellij.openapi.vfs.VirtualFileManager.getInstance(VirtualFileManager.java:44)
	at com.intellij.history.integration.LocalHistoryImpl.disposeComponent(LocalHistoryImpl.java:133)
	at com.intellij.history.integration.LocalHistoryImpl$1.run(LocalHistoryImpl.java:64)
	at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:62)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Shutdown tracker" java.lang.AssertionError: @NotNull method com/intellij/openapi/vfs/VirtualFileManager.getInstance must not return null
	at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:56)
	at com.intellij.testFramework.TestLogger.error(TestLogger.java:67)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:65)
	at java.lang.Thread.run(Thread.java:745)

**Comment by joaoandremartins** [comment]
@patflynn are you still getting this?

I'm getting other exceptions in the tests, but not this one.

**Comment by patflynn** [comment]
@joaoandremartins good point. I haven't seen this in a while. I'm going to close it.
