### ISSUE TITLE
memory leak detected during debugger tests

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#212]
java.lang.RuntimeException: Memory leak detected: com.google.gct.idea.debugger.ui.ExitDialog@5d5857f8 of class class com.intellij.openapi.ui.DialogWrapper$1
See the cause for the corresponding Disposer.register() stacktrace:

        at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:209)
        at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:125)
        at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:121)
        at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:323)
        at com.intellij.openapi.application.impl.ApplicationImpl.access$400(ApplicationImpl.java:87)
        at com.intellij.openapi.application.impl.ApplicationImpl$5$1.run(ApplicationImpl.java:283)
        at com.intellij.openapi.util.ShutDownTracker$2.run(ShutDownTracker.java:171)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.openapi.util.ShutDownTracker$2.run(ShutDownTracker.java:171)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: Memory leak detected: com.google.gct.idea.debugger.ui.ExitDialog@5d5857f8 of class class com.intellij.openapi.ui.DialogWrapper$1
See the cause for the corresponding Disposer.register() stacktrace:

        at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:209)
        ... 23 more
Caused by: java.lang.Throwable
        at com.intellij.openapi.util.objectTree.ObjectTree.getOrCreateNodeFor(ObjectTree.java:101)
        at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:62)
        at com.intellij.openapi.util.Disposer.register(Disposer.java:81)
        at com.intellij.openapi.util.Disposer.register(Disposer.java:75)
        at com.intellij.util.Alarm.<init>(Alarm.java:140)
        at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:298)
        at com.google.gct.idea.debugger.ui.ExitDialog.<init>(Unknown Source)
        at com.google.gct.idea.debugger.ui.ExitDialogTest$1.run(ExitDialogTest.java:27)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        ... 16 more
ERROR: Memory leak detected: com.google.gct.idea.debugger.ui.ExitDialog@5d5857f8 of class class com.intellij.openapi.ui.DialogWrapper$1
See the cause for the corresponding Disposer.register() stacktrace:

java.lang.AssertionError: Memory leak detected: com.google.gct.idea.debugger.ui.ExitDialog@5d5857f8 of class class com.intellij.openapi.ui.DialogWrapper$1
See the cause for the corresponding Disposer.register() stacktrace:

        at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:56)
        at com.intellij.testFramework.TestLogger.error(TestLogger.java:67)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
        at com.intellij.ide.plugins.PluginManager.processException(PluginManager.java:134)
        at com.intellij.ide.IdeEventQueue.processException(Ideeue.java:403)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:737)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0 14.1.4#IC-141.1532.4, eap:false 14.1.4#IC-141.1532.4, eap:false" java.lang.AssertionError: Memory leak detected: com.google.gct.idea.debugger.ui.ExitDialog@5d5857f8 of class class com.intellij.openapi.ui.DialogWrapper$1
See the cause for the corresponding Disposer.register() stacktrace:

        at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:56)
        at com.intellij.testFramework.TestLogger.error(TestLogger.java:67)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
        at com.intellij.ide.plugins.PluginManager.processException(PluginManager.java:134)
        at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.java:403)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by patflynn** [comment]
Elliotte can you take a quick look at this?  I'm concerned this may have been recently introduced as I don't recall seeing this during test runs before.

**Comment by elharo** [comment]
almost certainly new since that class didn't exist until yesterday :-)

On Tue, Nov 10, 2015 at 2:18 PM, Patrick Flynn <notifications@github.com>
wrote:

> Elliotte can you take a quick look at this? I'm concerned this may have
> been recently introduced as I don't recall seeing this during test runs
> before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-intellij/issues/212#issuecomment-155536376>
> .
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com
