### ISSUE TITLE
Exception logged during cloud debugger session

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#232]
Steps to reproduce:
1) in IJ with plugin
2) checkout ct4ij-cloud-debugger-demo (only available to project collaborators)
3) create cdb debug config connecting to above project
4) Start run configuration
5) observe below exception in IDE logs.

Exception in thread "list breakpoints" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.pruneBreakpointCache(CloudDebugProcessStateController.java:411)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.waitForChanges(CloudDebugProcessStateController.java:349)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$4.run(CloudDebugProcessStateController.java:266)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$RunnableTimerTask.run(CloudDebugProcessStateController.java:442)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)

**Comment by elharo** [comment]
That's really weird. It seems to be saying there's no keySet method in ConcurrentHashMap, which is nigh impossible, Just maybe a class loader problem?

**Comment by elharo** [comment]
And google is our friend:

https://gist.github.com/AlainODea/1375759b8720a3f9f094

I twould have taken me a long time to figure that one out on my own.

**Comment by patflynn** [comment]
This is another reason why we need to configure Travis or something like it
to prepare our release binaries in a safe and reliable manner.
