### ISSUE TITLE
Error in travis log during test run

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#255]
ERROR: Not disposed pointer: file:///home/travis/build/GoogleCloudPlatform/gcloud-intellij/core-plugin/testData/lib
--------------Creation trace: 
java.lang.Throwable: parent = 'com.intellij.openapi.util.Disposer$2@14d6edc8' (class com.intellij.openapi.util.Disposer$2); URL=<file:///home/travis/build/GoogleCloudPlatform/gcloud-intellij/core-plugin/testData/lib,file:///home/travis/build/GoogleCloudPlatform/gcloud-intellij/core-plugin/testData/lib>
	at com.intellij.openapi.vfs.impl.VirtualFilePointerImpl.<init>(VirtualFilePointerImpl.java:40)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.getOrCreate(VirtualFilePointerManagerImpl.java:266)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.create(VirtualFilePointerManagerImpl.java:218)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.create(VirtualFilePointerManagerImpl.java:163)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.create(VirtualFilePointerContainerImpl.java:266)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.add(VirtualFilePointerContainerImpl.java:124)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.addJarDirectory(LibraryImpl.java:481)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.addJarDirectory(LibraryImpl.java:462)
	at com.google.gct.idea.appengine.validation.EndpointTestBase$1.run(EndpointTestBase.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
	at com.google.gct.idea.appengine.validation.EndpointTestBase.addEndpointSdkToProject(EndpointTestBase.java:56)
	at com.google.gct.idea.appengine.validation.EndpointTestBase.setUp(EndpointTestBase.java:43)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:358)
	at com.intellij.testFramework.UsefulTestCase$3.run(UsefulTestCase.java:419)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:25)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:23)
	at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$a15fd9f8.run(EdtTestUtil.kt)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:216)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:678)
	at java.awt.EventQueue.access$400(EventQueue.java:96)
	at java.awt.EventQueue$2.run(EventQueue.java:639)
	at java.awt.EventQueue$2.run(EventQueue.java:637)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:648)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
-------------Own trace:

**Comment by patflynn** [comment]
@loosebazooka can you pull your aosp fix in?
