### ISSUE TITLE
Usage tracking causing class loading error

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#260]
Exception class name: java.lang.LinkageError: loader constraint violation: when resolving method "org.apache.http.client.utils.HttpClientUtils.closeQuietly(Lorg/apache/http/client/HttpClient;)V" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, com/google/gct/stats/GoogleUsageTracker$1, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, org/apache/http/client/utils/HttpClientUtils, have different Class objects for the type org/apache/http/client/HttpClient used in the signature
Exception message: loader constraint violation: when resolving method "org.apache.http.client.utils.HttpClientUtils.closeQuietly(Lorg/apache/http/client/HttpClient;)V" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, com/google/gct/stats/GoogleUsageTracker$1, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, org/apache/http/client/utils/HttpClientUtils, have different Class objects for the type org/apache/http/client/HttpClient used in the signature
Stack trace:
java.lang.LinkageError: loader constraint violation: when resolving method "org.apache.http.client.utils.HttpClientUtils.closeQuietly(Lorg/apache/http/client/HttpClient;)V" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, com/google/gct/stats/GoogleUsageTracker$1, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, org/apache/http/client/utils/HttpClientUtils, have different Class objects for the type org/apache/http/client/HttpClient used in the signature
	at com.google.gct.stats.GoogleUsageTracker$1.run(GoogleUsageTracker.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by patflynn** [comment]
I'm working on a fix right now.
