### ISSUE TITLE
Cloud Debugger spits out a lot of errors to the logs and eventually crashes IJ out of permgen

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#286]
[1067205]   WARN - oudDebugProcessStateController - exception listing breakpoints 
com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "The operation was aborted.",
    "reason" : "aborted"
  } ],
  "message" : "The operation was aborted.",
  "status" : "ABORTED"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.queryServerForBreakpoints(CloudDebugProcessStateController.java:366)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.waitForChanges(CloudDebugProcessStateController.java:325)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$4.run(CloudDebugProcessStateController.java:266)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$RunnableTimerTask.run(CloudDebugProcessStateController.java:442)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
[1147820]   WARN - oudDebugProcessStateController - exception listing breakpoints 
com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "The operation was aborted.",
    "reason" : "aborted"
  } ],
  "message" : "The operation was aborted.",
  "status" : "ABORTED"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.queryServerForBreakpoints(CloudDebugProcessStateController.java:366)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.waitForChanges(CloudDebugProcessStateController.java:325)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$4.run(CloudDebugProcessStateController.java:266)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$RunnableTimerTask.run(CloudDebugProcessStateController.java:442)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
[1228429]   WARN - oudDebugProcessStateController - exception listing breakpoints 
com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "The operation was aborted.",
    "reason" : "aborted"
  } ],
  "message" : "The operation was aborted.",
  "status" : "ABORTED"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.queryServerForBreakpoints(CloudDebugProcessStateController.java:366)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.waitForChanges(CloudDebugProcessStateController.java:325)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$4.run(CloudDebugProcessStateController.java:266)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$RunnableTimerTask.run(CloudDebugProcessStateController.java:442)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
[1356527]   WARN - oudDebugProcessStateController - exception listing breakpoints 
com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "The operation was aborted.",
    "reason" : "aborted"
  } ],
  "message" : "The operation was aborted.",
  "status" : "ABORTED"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.queryServerForBreakpoints(CloudDebugProcessStateController.java:366)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.waitForChanges(CloudDebugProcessStateController.java:325)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$4.run(CloudDebugProcessStateController.java:266)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$RunnableTimerTask.run(CloudDebugProcessStateController.java:442)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
[1356527]   WARN - oudDebugProcessStateController - exception listing breakpoints 
com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "The operation was aborted.",
    "reason" : "aborted"
  } ],
  "message" : "The operation was aborted.",
  "status" : "ABORTED"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.queryServerForBreakpoints(CloudDebugProcessStateController.java:366)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.waitForChanges(CloudDebugProcessStateController.java:325)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$4.run(CloudDebugProcessStateController.java:266)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$RunnableTimerTask.run(CloudDebugProcessStateController.java:442)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
[1437135]   WARN - oudDebugProcessStateController - exception listing breakpoints 
com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "The operation was aborted.",
    "reason" : "aborted"
  } ],
  "message" : "The operation was aborted.",
  "status" : "ABORTED"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.queryServerForBreakpoints(CloudDebugProcessStateController.java:366)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.waitForChanges(CloudDebugProcessStateController.java:325)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$4.run(CloudDebugProcessStateController.java:266)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$RunnableTimerTask.run(CloudDebugProcessStateController.java:442)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
[1437135]   WARN - oudDebugProcessStateController - exception listing breakpoints 
com.google.api.client.googleapis.json.GoogleJsonResponseException: 409 Conflict
{
  "code" : 409,
  "errors" : [ {
    "domain" : "global",
    "message" : "The operation was aborted.",
    "reason" : "aborted"
  } ],
  "message" : "The operation was aborted.",
  "status" : "ABORTED"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.queryServerForBreakpoints(CloudDebugProcessStateController.java:366)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController.waitForChanges(CloudDebugProcessStateController.java:325)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$4.run(CloudDebugProcessStateController.java:266)
	at com.google.gct.idea.debugger.CloudDebugProcessStateController$RunnableTimerTask.run(CloudDebugProcessStateController.java:442)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
Exception in thread "Performance watcher" java.lang.OutOfMemoryError: PermGen space

**Comment by patflynn** [comment]
actually it looks like they might be unrelated. If I go to Java 8 I still see the exceptions but don't get the permgen issue. We probably need to make sure our gradle runIdea invocations get a higher max permgen

**Comment by joaoandremartins** [comment]
I'm still getting these 409's, which appear to impact getting snapshots since I'm not getting any.

**Comment by patflynn** [comment]
are you testing this with your personal project?

**Comment by joaoandremartins** [comment]
Yes

**Comment by patflynn** [comment]
Can you check whether cloud debugging is working in pantheon?

**Comment by akerekes** [comment]
The 409's are received from the cloud debugger backend as expected response when the long polling queries time out or there is data available to retrieve. 409's won't be logged after #459 is fixed.
