### ISSUE TITLE
No network triggers errors in the IDE during project selection

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#323]
Exception loading projects for null: accounts.google.com
java.net.UnknownHostException: accounts.google.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1103)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:997)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1281)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1256)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
	at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:570)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:247)
	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.gct.idea.elysium.GoogleUserModelItem.loadUserProjects(GoogleUserModelItem.java:132)
	at com.google.gct.idea.elysium.GoogleUserModelItem.access$100(GoogleUserModelItem.java:43)
	at com.google.gct.idea.elysium.GoogleUserModelItem$1.run(GoogleUserModelItem.java:97)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by elharo** [comment]
Not hugely surprising. What do you think we should do about this? Disable the widget if there's no network connection? But then how would we reenable?

**Comment by patflynn** [comment]
We shouldn't log an error. It's not a bug. We should just tell the user
they're offline and we can't proceed.

**Comment by elharo** [comment]
What's the UI for this going to look like? How about a simple alert dialog?

**Comment by elharo** [comment]
![screenshot from 2015-12-21 10 36 37](https://cloud.githubusercontent.com/assets/1005544/11934291/3cbe4c96-a7cf-11e5-8f48-1562ba170598.png)

**Comment by patflynn** [comment]
How about a slightly more user friendly message?

Something like:

"Could not connect to Google. Please make sure you have a working internet
connection"

**Comment by elharo** [comment]
On Mon, Dec 21, 2015 at 10:48 AM, Patrick Flynn <notifications@github.com>
wrote:

> How about a slightly more user friendly message?
>
> Something like:
>
> "Could not connect to Google. Please make sure you have a working internet
> connection"
>

done


-- 
Elliotte Rusty Harold
elharo@macfaq.com
