### ISSUE TITLE
Memory leak when running test suite via command line

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#410]
When running ./gradlew clean test, a memory leak is reported. Reproducible on linux, but not on mac.

The source test of this error appears to be CloudDebugGlobalPollerTest. See exception / stack trace below:

java.lang.RuntimeException: Memory leak detected: com.google.gct.idea.testing.TestUtils$PluginMockApplication@63828d7a of class class com.google.gct.idea.testing.TestUtils$PluginMockApplication
See the cause for the corresponding Disposer.register() stacktrace:
at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:209)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:124)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:120)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:308)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$400(ApplicationImpl.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$5$1.run(ApplicationImpl.java:268)
	at com.intellij.openapi.util.ShutDownTracker$2.run(ShutDownTracker.java:172)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by loosebazooka** [comment]
How are you identifying the test that is causing is this?

**Comment by loosebazooka** [comment]
`@Ignore` the IntelliJGoogleLoginMessageExtenderTest and this seems to not happen.

However running just that test without anything else also makes things work.
```
./gradlew clean :google-cloud-tools-plugin:test -Dtest.single=IntellijGoogleLoginMessageExtenderTest
```

wat?

**Comment by etanshaul** [comment]
@loosebazooka from the stack trace you can see that there is an issue with TestUtils which is used only by BasePluginTestCase. There were 2 candidate tests (at the time of writing this issue..now there are more inheritors of this class):

- CloudDebugGlobalPollerTest
- CloudDebugProcessHandlerTest

I could then isolate it to CloudDebugProcessHandlerTest. 

You mentioned IntelliJGoogleLoginMessageExtenderTest which also extends BasePluginTestCase - this test was created after the issue was filed and could also be problematic. The issue has to do with interaction between different tests which explains why running the test alone doesn't cause it.

**Comment by etanshaul** [comment]
My last comment is a bit misleading - I think problem is with BasePluginTestCase - the tests that implement this class seem to be order-dependent causing strange non-reproducible failures.

**Comment by akerekes** [comment]
I'm pretty sure this is caused by the change I've done in the
BasePluginTestCase to restore the IJ created application object after the
test case has run with a mocked application (to ensure that our existing
test cases will not break if they run after a test inherited from
BasePluginTestCase). However I was not able to find where is the object
created that is not disposed properly and thus causes the teardown phase to
complain about memory leak.

**Comment by patflynn** [comment]
@etanshaul are you working on this?  I'm thinking of giving it to Mike as a starter bug.

**Comment by etanshaul** [comment]
Sure go for it. Andras and I did a little digging earlier and attached what
we found so far to the issue.

**Comment by patflynn** [comment]
Hey Mike do you want to check this out?

**Comment by meltsufin** [comment]
Sure, I'll give it a shot.

**Comment by meltsufin** [comment]
It looks like our `BasePluginTestCase` is indeed not cleaning up something. I've been able to isolate the problem to the `setup` and `tearDown` methods. It also seems to only manifest itself when followed by a test that uses `setUp` and `tearDown` of IntelliJ's `PlatformTestCase`.
If you run just these two tests below, you get the same Memory leak error.
```
public class TestA extends BasePluginTestCase {
    @Test
    public void test() {
        System.out.println("Test A executed.");
    }
}
```

```
public class TestB extends PlatformTestCase {
    public void test() {
        System.out.println("Test B executed.");
    }
}
```
Continuing to investigate...

**Comment by meltsufin** [comment]
I found a way to fix it, but I'm still not completely sure why this works.
If you add `com.intellij.testFramework.TestRunnerUtil.replaceIdeEventQueueSafely();` to the top of our `BasePluginTestCase.setup()`, the memory leak error goes away.

I found this in the internals of the IntelliJ's test framework. More specifically, this is used in the `com.intellij.testFramework.UsefulTestCase`, which is the base class for a collection of other utility test classes, one of which is `PlatformTestCase` that we use.

I also stumbled upon `PlatformLiteFixture` which is also a subclass of `UsefulTestCase` and seems to create a `MockApplicationEx`, similarly to our `BasePluginTestCase`.

@patflynn Is there any reason why we didn't use the `PlatformLiteFixture` for our `BasePluginTestCase` other than the fact that it's JUnit3 vs our `BasePluginTestCase` being JUnit4?

**Comment by patflynn** [comment]
I kind of understand what's going on in BasePluginTestCase, and I like
being able to use Junit 4, and apart from this exception that shows up in
our logs, it seems to work pretty well.  If adding that call fixes the
issue, and UsefulTestCase does the same, I have no objection to inserting
it and forgetting about it.
