### ISSUE TITLE
another account plugin crash

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#623]
@meltsufin is this possibly related to the issue you were looking into?

Original Description (lang: ):
Argument for @NotNull parameter 'userEmail' of com/google/cloud/tools/intellij/login/CredentialedUserRoster.setActiveUser must not be null
Submitted by: <anonymous>
Submitted on: 2016-04-12 14:33 UTC
Product Version: 2016.1.1
Package Name: com.google.gct.idea
Package Version Name: 2016.1.1
Device Model: unknown
Bugs (0)
Crash Data
Exception class name: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'userEmail' of com/google/cloud/tools/intellij/login/CredentialedUserRoster.setActiveUser must not be null
Exception message: Argument for @NotNull parameter 'userEmail' of com/google/cloud/tools/intellij/login/CredentialedUserRoster.setActiveUser must not be null
Stack trace:
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'userEmail' of com/google/cloud/tools/intellij/login/CredentialedUserRoster.setActiveUser must not be null
	at com.google.cloud.tools.intellij.login.CredentialedUserRoster.setActiveUser(CredentialedUserRoster.java)
	at com.google.cloud.tools.intellij.login.CredentialedUserRoster.addUser(CredentialedUserRoster.java:139)
	at com.google.cloud.tools.intellij.login.IntellijGoogleLoginService$1.notifyOnComplete(IntellijGoogleLoginService.java:217)
	at com.google.cloud.tools.intellij.login.IntellijGoogleLoginService$1.onSuccess(IntellijGoogleLoginService.java:201)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:361)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:283)
	at com.intellij.openapi.progress.Task.queue(Task.java:83)
	at com.google.cloud.tools.intellij.login.IntellijGoogleLoginService.logIn(IntellijGoogleLoginService.java:172)
	at com.google.cloud.tools.intellij.elysium.UserSelector$PopupPanel.doLogin(UserSelector.java:204)
	at com.google.cloud.tools.intellij.login.ui.GoogleLoginEmptyPanel$1.actionPerformed(GoogleLoginEmptyPanel.java:53)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:792)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1661)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1610)
	at git4idea.DialogManager.showDialog(DialogManager.java:56)
	at git4idea.DialogManager.show(DialogManager.java:23)
	at com.google.cloud.tools.intellij.git.GcpHttpAuthDataProvider$1.run(GcpHttpAuthDataProvider.java:81)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:160)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Throw file name: CredentialedUserRoster.java
Throw line number: -1
Throw class name: com.google.cloud.tools.intellij.login.CredentialedUserRoster
Throw method name: setActiveUser
Package Information
Package name: com.google.gct.idea
Process name: Cloud Tools for IntelliJ
Package version name: 2016.1.1
Installer package name: Cloud Tools for IntelliJ
Build
Product: Cloud Tools for IntelliJ
Model name: unknown
Device: unknown
Build ID: 2016.1.1
Build Type: unknown
Release: 2016.1.1
System Data
Timestamp (UTC): 2016-04-12 14:33
Timestamp (raw): 1460471633250
Product Specific Data

**Comment by meltsufin** [comment]
This looks exactly the same as #601 and has been fixed.
