### ISSUE TITLE
user reported error:

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#650]
@etanshaul my guess is that this is caused by an update of the cloud tools plugin without updating the account plugin.  This is going to be an issue for us.  Is it possible to check the version of the account plugin and display a warning to the user if it's not what it should be?

stacktrace:
java.lang.NoSuchMethodError: com.google.cloud.tools.intellij.login.GoogleLoginService.logInIfNot()V
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineCloudType$AppEngineServerConnector.connect(AppEngineCloudType.java:120)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl.connectIfNeeded(ServerConnectionImpl.java:364)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl.connect(ServerConnectionImpl.java:93)
	at com.intellij.remoteServer.impl.runtime.ui.tree.actions.RemoteServerConnectAction.doActionPerformed(RemoteServerConnectAction.java:41)
	at com.intellij.remoteServer.impl.runtime.ui.tree.actions.RemoteServerConnectAction.doActionPerformed(RemoteServerConnectAction.java:23)
	at com.intellij.remoteServer.impl.runtime.ui.tree.actions.ServersTreeAction.doActionPerformed(ServersTreeAction.java:114)
	at com.intellij.remoteServer.impl.runtime.ui.tree.actions.ServersTreeAction.doActionPerformed(ServersTreeAction.java:109)
	at com.intellij.remoteServer.impl.runtime.ui.tree.actions.ServersTreeAction.actionPerformed(ServersTreeAction.java:89)
	at com.intellij.remoteServer.impl.runtime.ui.ServersToolWindowContent$2.onDoubleClick(ServersToolWindowContent.java:114)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by etanshaul** [comment]
It would be nice if there was a mechanism for linking plugins at the repository level (something like a dependency) but there isn't as far as I know. I'll look into this.

**Comment by etanshaul** [comment]
Sadly, it looks like a plugin cannot depend on a specific version of another plugin:

**Comment by etanshaul** [comment]
A possible solution is to show a balloon warning on the account tools avatar icon after initialization if the the account tools plugin version does not match the cloud tools version. Here is a screenshot with placeholder wording):

![image](https://cloud.githubusercontent.com/assets/1735744/14792280/88b647fe-0ae7-11e6-8cf6-80107bb03448.png)

**Comment by etanshaul** [comment]
On second thought, I prefer the approach of showing an unattached dialog after initialization which could link into the plugin menu. Something similar to this message which links into the repositories menu:

![image](https://cloud.githubusercontent.com/assets/1735744/14792414/11bd09e8-0ae8-11e6-98b1-e0cfbea2f4cc.png)

**Comment by patflynn** [comment]
That ain't crazy.  Is there a way to include a link to the 'check for
updates' action that's in the help menu?

**Comment by etanshaul** [comment]
Good idea. I'll look into what we can do.
