### ISSUE TITLE
random stacktrace might be worth looking into

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#704]
INFO: submitting command: /usr/local/google/home/paflynn/lang/java/jdk1.8.0_60/jre/bin/java -cp /usr/local/google/home/paflynn/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.admin.AppCfg --enable_jar_splitting stage /usr/local/google/home/paflynn/IdeaProjects/appengine-wiz/out/artifacts/appengine_wiz_war_exploded /tmp/gae-mvm1.tmp
Exception in thread "wait-for-exit" java.lang.IllegalArgumentException: Deployable /tmp/gae-mvm1.tmp/app.yaml does not exist.
	at com.google.cloud.tools.app.impl.cloudsdk.CloudSdkAppEngineDeployment.deploy(CloudSdkAppEngineDeployment.java:53)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineDeployAction.deploy(AppEngineDeployAction.java:202)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineDeployAction.access$000(AppEngineDeployAction.java:56)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineDeployAction$1.exit(AppEngineDeployAction.java:94)
	at com.google.cloud.tools.app.impl.cloudsdk.internal.process.DefaultProcessRunner$3.run(DefaultProcessRunner.java:158)
May 27, 2016 12:02:16 PM com.google.cloud.tools.app.impl.cloudsdk.internal.sdk.CloudSdk outputCommand
INFO: submitting command: /usr/local/google/home/paflynn/lang/java/jdk1.8.0_60/jre/bin/java -cp /usr/local/google/home/paflynn/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.admin.AppCfg --enable_jar_splitting stage /usr/local/google/home/paflynn/IdeaProjects/appengine-wiz/out/artifacts/appengine_wiz_war_exploded /tmp/gae-mvm2.tmp
Exception in thread "standard-out" java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4298)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:2997)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:2955)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2725)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineAction.consoleLogLn(AppEngineAction.java:181)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineAction$ConsoleOutputLineListener.outputLine(AppEngineAction.java:187)
	at com.google.cloud.tools.app.impl.cloudsdk.internal.process.DefaultProcessRunner$1.run(DefaultProcessRunner.java:116)
May 27, 2016 12:02:18 PM com.google.cloud.tools.app.impl.cloudsdk.internal.sdk.CloudSdk outputCommand
INFO: submitting command: /usr/local/google/home/paflynn/google-cloud-sdk/bin/gcloud preview app deploy /tmp/gae-mvm2.tmp/app.yaml --project paflynn-demo-project-5 --promote --quiet --credential-file-override /tmp/tmp_google_application_default_credential5json --format json
[2128233]   WARN - pl.local.NativeFileWatcherImpl - Watcher terminated with exit code 0

**Comment by etanshaul** [comment]
Is this running off of master or the AE standard deployment branch? If its the latter, this should be fixed (so check to make sure you've pulled).

**Comment by etanshaul** [comment]
This happens because occasionally the gcloud output will return characters that need to be escaped for String.format.

**Comment by patflynn** [comment]
ah that's it.
