### ISSUE TITLE
set group display name in tests

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-intellij#80]
Many of our validation tests throw an exception like this:

ERROR: class com.google.gct.idea.appengine.validation.ResourceParameterInspection: group display name should be overridden or configured via XML class com.google.gct.idea.appengine.validation.ResourceParameterInspection
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.codeInspection.InspectionProfileEntry.getGroupDisplayName(InspectionProfileEntry.java:201)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getGroupDisplayName(InspectionToolWrapper.java:132)
	at com.intellij.codeInspection.ui.InspectionResultsView.addTool(InspectionResultsView.java:464)
	at com.intellij.codeInspection.ui.DefaultInspectionToolPresentation.addProblemElement(DefaultInspectionToolPresentation.java:234)

This isn't really a failure but it does hide real failures. Figure out how to fix this.

**Comment by elharo** [comment]
To fix this we need to override getGroupDisplayName in each of our inspections:

 /**
   * @see InspectionEP#groupDisplayName
   * @see InspectionEP#groupKey
   * @see InspectionEP#groupBundle
   */
  @Nls
  @NotNull
  public String getGroupDisplayName() {
    if (myNameProvider != null) {
      final String name = myNameProvider.getDefaultGroupDisplayName();
      if (name != null) {
        return name;
      }
    }
    LOG.error(getClass() + ": group display name should be overridden or configured via XML " + getClass());
    return "";
  }


I'm trying to figur eout what these names should be set to. JetBrains discussion here:

https://devnet.jetbrains.com/thread/473590
