### ISSUE TITLE
NoSuchMethodError exception in 2016.2.1

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#813]
Exception class name: java.lang.NoSuchMethodError: com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/Collection;
Exception message: com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/Collection;
Stack trace:
java.lang.NoSuchMethodError: com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/Collection;
	at com.google.cloud.tools.intellij.git.UploadSourceAction.performFirstCommitIfRequired(UploadSourceAction.java:470)
	at com.google.cloud.tools.intellij.git.UploadSourceAction.access$500(UploadSourceAction.java:93)
	at com.google.cloud.tools.intellij.git.UploadSourceAction$1.run(UploadSourceAction.java:211)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by etanshaul** [comment]
app.name.version: IntelliJ IDEA
app.version.major: 2016
app.version.minor: 2.1
java.version: 1.8.0_76-release
